cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'
urlpatterns = [
    path('add/<uuid:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<uuid:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<uuid:product_id>/', views.full_remove, name='full_remove'),
]

onlineshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('accounts/', include('accounts.urls')),
                  path('', include('shop.urls')),
                  path('search/', include('search_app.urls')),
                  path('cart/', include('cart.urls')),
                  path('order/', include('order.urls')),
                  path('vouchers/', include('vouchers.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('thanks/<int:order_id>/', views.thanks, name='thanks'),
    path('history/', views.OrderHistory.as_view(), name='order_history'),
    path('<int:order_id>/', views.OrderDetail.as_view(), name='order_detail'),


]

search_app/urls.py
from django.urls import path
from .views import SearchResultsListView

app_name='search_app'

urlpatterns = [
 path('', SearchResultsListView.as_view(), name='searchResult'),
]

shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'

urlpatterns = [
    path('', views.index_page, name='index'),
    path('shop/shop_menu', views.prod_list, name='shop_menu'),
    path('contact', views.contact_page, name='contact'),
    path('<uuid:category_id>/', views.prod_list, name='products_by_category'),
    path('<uuid:category_id>/<uuid:product_id>/', views.product_detail, name= 'product_detail'),
]

shop/models.py
from django.db import models
import uuid
from django.urls import reverse

class Category(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    name = models.CharField(max_length=250, unique=True)
    description = models.TextField(blank = True)
    image = models.ImageField(upload_to = 'category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('shop:products_by_category', args=[self.id])

    def __str__(self):
        return self.name
    
class Allergen(models.Model):
    name = models.CharField(max_length=50)

class Product(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    
    name = models.CharField(max_length=250, unique=True)
    description = models.TextField(blank = True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to = 'product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, blank = True, null= True)
    updated = models.DateTimeField(auto_now=True, blank = True, null= True)
    expiry_date = models.DateField(null=True, blank=True)
    allergens_text = models.CharField(max_length=255, blank=True, help_text="Enter allergens separated by commas")

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.category.id, self.id])

    def __str__(self):
        return self.name

shop/forms.py
# forms.py
from django import forms

class CommentForm(forms.Form):
    name = forms.CharField(max_length=100, label='Your Name')
    email = forms.EmailField(label='Your Email')
    comment = forms.CharField(widget=forms.Textarea, label='Your Comment')

shop/views.py
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.shortcuts import render, get_object_or_404

from .models import Category, Product


def index_page(request):
    return render(request, 'index.html', {})


def contact_page(request):
    return render(request, 'contact.html', {})


def pizzas_category(request):
    pizza_products = Product.objects.filter(category__name='Chicken')
    return render(request, 'shop/pizzas_category.html', {'pizza_products': pizza_products})


def chicken_category(request):
    chicken_products = Product.objects.filter(category__name='Chicken')
    return render(request, 'shop/chicken_category.html', {'chicken_products': chicken_products})


def sides_category(request):
    sides_products = Product.objects.filter(category__name='Sides')
    return render(request, 'shop/sides_category.html', {'sides_products': sides_products})


def drinks_category(request):
    drinks = Product.objects.filter(category__name='Drinks')
    paginator = Paginator(drinks, 12)  # Adjust the number of items per page as needed

    page = request.GET.get('page')
    try:
        drinks = paginator.page(page)
    except PageNotAnInteger:
        drinks = paginator.page(1)
    except EmptyPage:
        drinks = paginator.page(paginator.num_pages)

    return render(request, 'shop/drinks_category.html', {'drinks': drinks})


def prod_list(request, category_id=None):
    category = None
    products = Product.objects.filter(available=True)

    # Check if the category_id is provided
    if category_id:
        # If the category_id is "pizzas", set the category to the Pizza category
        if category_id == "pizzas":
            category = get_object_or_404(Category, name="Pizzas")
        else:
            category = get_object_or_404(Category, id=category_id)

        # Filter products based on the selected category
        products = Product.objects.filter(category=category, available=True)

    paginator = Paginator(products, 6)
    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1

    try:
        products = paginator.page(page)
    except (EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)

    return render(request, 'shop/category.html', {'category': category, 'prods': products})


def product_detail(request, category_id, product_id):
    product = get_object_or_404(Product, category_id=category_id, id=product_id)
    return render(request, 'shop/product.html', {'product': product})

shop/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet">
    <!--  Owl css -->
    <link rel="stylesheet" type="text/css" href="static/css/owl.carousel.min.css">
    <link rel="stylesheet" type="text/css" href="static/css/owl.theme.default.min.css">
    <!-- Bootstrap 5.3.0 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous"/>
    <!-- Font Awesome -->
    <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
    <!-- Custom css -->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <meta name="description"
          content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>

</head>
<body>
<header class="main_menu home_menu">
    {% include 'navbar.html' %}
</header>
{% block content %}
{% endblock %}
{% include 'footer.html' %}
<!-- JavaScript Bundle with Popper -->
<script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</body>
</html>

shop/templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Scooby`s Pizza
{% endblock %}

{% block metadescription %}
Welcome to Scooby`s Pizza
{% endblock %}

{% block content %}
<section class="breadcrumb breadcrumb_bg"
         style="background-image: url('{% static 'images/Contact.png' %}');background-position: center;background-repeat: no-repeat;background-size: cover;">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="breadcrumb_iner">
                    <div class="breadcrumb_iner_item">
                        <h1>Contact Us</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="contact-section padding_top">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2 class="contact-title">Get in Touch</h2>
            </div>
            <div class="col-lg-8">
                <form class="form-contact contact_form" id="contactForm">
                    <div class="row">
                        <div class="col-12">
                            <div class="form-group">
                                <textarea class="form-control w-100" name="message" id="message" cols="30" rows="9"
                                          onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Message'"
                                          placeholder="Enter Message"></textarea>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <input class="form-control" name="name" id="name" type="text"
                                       onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter your name'"
                                       placeholder="Enter your name">
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <input class="form-control" name="email" id="email" type="email"
                                       onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'"
                                       placeholder="Enter email address">
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group">
                                <input class="form-control" name="subject" id="subject" type="text"
                                       onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Subject'"
                                       placeholder="Enter Subject">
                            </div>
                        </div>
                    </div>
                    <div class="form-group mt-3">
                        <a href="#" class="btn_3 button-contactForm">Send Message</a>
                    </div>
                </form>
            </div>
            <div class="col-lg-4">
                <div class="media contact-info">
                    <span class="contact-info__icon"><i class="ti-home"></i></span>
                    <div class="media-body">
                        <h3>Tallaght, Ireland</h3>
                        <p>Technological University Dublin</p>
                    </div>
                </div>
                <div class="media contact-info">
                    <span class="contact-info__icon"><i class="ti-tablet"></i></span>
                    <div class="media-body">
                        <h3>00 123 456 789</h3>
                        <p>Mon to Fri 9am to 9pm</p>
                    </div>
                </div>
                <div class="media contact-info">
                    <span class="contact-info__icon"><i class="ti-email"></i></span>
                    <div class="media-body">
                        <h3>support@scooby.com</h3>
                        <p>Send us your query anytime!</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

shop/templates/footer.html
<footer>
    <div class="container">
        <!-- footer top menus -->
        <div class="row">
            <div class="col-lg-2">
                <div class="f-item">
                    <h4>Top Products</h4>
                    <ul>
                        <li><a href="">Tallagh Pizza</a></li>
                        <li><a href="">Greek Fusion</a></li>
                        <li><a href="">Mexican Spicy</a></li>
                        <li><a href="">Napoli Classic</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2">
                <div class="f-item">
                    <h4>Social Media</h4>
                    <ul>
                        <li><a href="">Facebook</a></li>
                        <li><a href="">Instagram</a></li>
                        <li><a href="">X</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- footer bottom copyright -->
    </div>
</footer>

shop/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Scooby`s Pizza
{% endblock %}

{% block metadescription %}
Welcome to Scooby`s Pizza
{% endblock %}

{% block content %}
<section class="banner">
    <div class="container">
        <div class="owl-carousel owl-theme">
            <div class="item"><
                <div class="row">
                    <div class="col-lg-4">
                        <div class="b-content">
                            <h1>The best pizza in Tallaght</h1>
                            <p>Tallaght's premier pizzeria delivers a mouthwatering experience with its thin, crispy
                                crust adorned with locally-sourced ingredients. The symphony of flavors, from juicy
                                tomatoes to savory cheeses, makes each bite satisfying and unforgettable. Whether dining
                                in or taking away, this pizza has become a local favorite, epitomizing tasteful
                                indulgence in Tallaght.</p>
                        </div>
                    </div>
                    <div class="col-lg-8">
                        <img src="{% static 'images/file-bXY7tFuoER4SJ4aSCnT0GZpn.png' %}" class="img-fluid">
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="b-content">
                            <h1>The Greek Fusion</h1>
                            <p>Immerse your taste buds in the flavors of the Mediterranean with a Greek-inspired pizza.
                                Feta cheese, Kalamata olives, sun-dried tomatoes, and a sprinkle of oregano adorn a
                                golden-brown crust, creating a harmonious blend of savory and tangy notes. This pizza is
                                a celebration of Mediterranean cuisine, transporting you to the azure shores and
                                sun-drenched landscapes that inspire its vibrant flavors.</p>
                        </div>
                    </div>
                    <div class="col-lg-8">
                        <img src="{% static 'images/file-u9MYJH5fd9YhEIf36ybTUDFD.png' %}" class="img-fluid">
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="b-content">
                            <h1>Mexican Spicy Fiesta</h1>
                            <p>Spice up your pizza experience with a Mexican-inspired creation that tantalizes the taste
                                buds. A zesty combination of chorizo, jalapeños, red onions, and fresh cilantro rests
                                atop a thin, crunchy crust, creating a fiesta of flavors. Each slice is a bold and
                                vibrant fusion of Mexican ingredients, delivering a mouthwatering experience that brings
                                the heat and excitement of Mexican cuisine to your plate.</p>
                        </div>
                    </div>
                    <div class="col-lg-8">
                        <img src="{% static 'images/file-wWsuPYS7kGvqDQwOsrfYBy8H.png' %}" class="img-fluid">
                    </div>
                </div>
                >
            </div>
            <div class="item">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="b-content">
                            <h1>Napoli's Classic Margherita</h1>
                            <p>Embark on a culinary journey to Napoli, where tradition and taste converge in a classic
                                Margherita pizza. The simplicity of fresh tomatoes, buffalo mozzarella, basil, and a
                                drizzle of olive oil on a perfectly blistered crust captures the essence of Neapolitan
                                pizza-making. Each bite is a homage to the rich history and timeless flavors that define
                                this beloved Italian creation.</p>
                        </div>
                    </div>
                    <div class="col-lg-8">
                        <img src="{% static 'images/file-YEnx1uWsKaZrzilLFpEpto0m.png' %}" class="img-fluid">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Owl js -->
<script type="text/javascript" src="static/js/jquery.min.js"></script>
<script type="text/javascript" src="static/js/owl.carousel.js"></script>
<!-- Custom Javascript -->
<script type="text/javascript" src="static/js/index.js"></script>
{% endblock %}

shop/templates/navbar.html
{% load static %}
<div class="container">
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <a class="navbar-brand" id="logo" href="{% url 'shop:index' %}"><img
                    src="{% static 'images/logo.png' %}"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav m-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'shop:index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'shop:contact' %}">Contact Us</a>
                    </li>
                    <li class="nav-item dropdown"> <!-- Wrap "Shop" link and dropdown menu in an <li> element -->
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Shop
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'shop:shop_menu' %}">All Products</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            {% for cat in links %}
                            <li><a class="dropdown-item" href="{{cat.get_absolute_url}}">{{cat.name}}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'order:order_history' %}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
                <form class="d-flex" action="{% url 'search_app:searchResult' %} " method="get">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
                    <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
</div>